 # Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: individual_postgres
    driver: postgresql
    proto: tcp
    user: admin
    passwd: admin1234
    host: localhost
    port: 5432
    dbName: stock_trading_dev
